sudo: required
services:
 - docker
script:
      - cd docker-images/mysql-xtrabackup
      - docker build .
      - cd ../docker-images/openemr
      - for D in *; do [ -d "${D}" ] && docker build "$D"; done
