sudo: required
services:
 - docker
script: |
      cd docker/mysql-xtrabackup
      echo travis: now building container mysql-xtrabackup
      docker build .
      echo travis: build mysql-xtrabackup complete
      cd ../../docker/openemr
      for D in *; do
            [ -d "${D}" ] || continue
            [[ "${D}" == "flex-3.7" || "${D}" == "flex-3.8" ]] && continue
            [[ "${D}" == "5.0.0" || "${D}" == "5.0.1" ]] && continue
            echo travis: now building container "${D}"
            docker build "$D"
            echo travis: build "${D}" complete
      done
