name: Production 7.0.1 Docker Build

on:
  workflow_dispatch:

jobs:
  build:
    # Only run from master branch on the main repository
    if: github.repository_owner == 'openemr' && github.repository == 'openemr/openemr-devops' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-22.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push 7.0.1 docker
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}:docker/openemr/7.0.1"
          tags: openemr/openemr:7.0.1
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          no-cache: true
